### ISSUE TITLE
pydest appears to have been removed from PyPI

### ISSUE THREAD

**Issue by chadwhitely** [jgayfer/pydest#13]
https://pypi.org/search/?q=pydest

Issue observed: Attempted to install via command `pip install pydest`. Received error `ERROR: Could not find a version that satisfies the requirement pydest (from versions: none)`

**Comment by jgayfer** [comment]
Give it another go, I believe it's because I had neglected to verify my email address 😬

**Comment by chadwhitely** [comment]
Awesome! It's back up, thanks!
