### ISSUE TITLE
"Can not load response cookies: Illegal key" error when running the find_user.py example

### ISSUE THREAD

**Issue by vcable** [jgayfer/pydest#16]
I was trying to run the find_user.py example file just to make sure everything worked, but every time I run it I get this error:
"Can not load response cookies: Illegal key"
I'm not sure why this is happening, since I put my API key into the script.

**Comment by jgayfer** [comment]
I can reproduce, and will investigate.

**Comment by MeridianPY** [comment]
Same issue, in my case when calling `search_destiny_player()`. Getting a response anyways.

**Comment by jgayfer** [comment]
Alright. So it looks like that warning shows up when we get a non success response from the API (and I believe it is nothing more than warning). I'm not entirely sure how to squelch this warning (or if it should be squelched).

However, there _was_ also an issue with the `finder_user.py` example, as it was still using `4` as the membership type for PC, which isn't used anymore with the migration to Steam. I've updated this example to use the new ID for Steam (`3`).

**Comment by rathmourn** [comment]
Interesting. I'm running into this issue with every API call I make via - even with successful responses. i.e. I get this error, but I still get actual data back from the end point. I'm inclined to think its something on Bungie's end? I've tried changing my API key even, but the "Illegal Key" hash in the response remains the same regardless. Unless there's an issue with how headers were passed all of a sudden?

**Comment by MeridianPY** [comment]
Same. I just worked more with the library, it's with every API call. As we all have the exact same issue, I also think this is on Bungie's end. But as long as we get our responses, I think you can disregard this issue.

**Comment by jgayfer** [comment]
Thanks for looking into this everyone. Will close for new as it appears that functionality is not impacted.
