### ISSUE TITLE
activity_manifest.py example no longer works

### ISSUE THREAD

**Issue by vpzed** [jgayfer/pydest#2]
The excellent addition of the _twos_comp_32 function broke the activity_manifest.py example since it contains the id column values instead of the hash property values from inside the json column.  The example should be updated with the hash values as shown below:

    activity1 = await destiny.decode_hash(2266954523, 'DestinyActivityDefinition')
    activity2 = await destiny.decode_hash(2287222467, 'DestinyActivityDefinition')

**Comment by jgayfer** [comment]
Good catch. I'll update them!

**Comment by jgayfer** [comment]
Fixed by a5fece33fa18799bbf75ab877dc8c50f0d65531a
