### ISSUE TITLE
support language zh-chs and ko in manifest.py still havent modified  yet ?

### ISSUE THREAD

**Issue by PilotSherlock** [jgayfer/pydest#23]
install from pip still not support zh-chs and ko,need to modifi it at local to support language

**Comment by jgayfer** [comment]
Thanks for the reminder!

I've merged the relevant PR, so this is now supported on master. I will deploy to PyPi next time I'm able.

**Comment by PilotSherlock** [comment]
Thank you

**Comment by jgayfer** [comment]
This is now on PyPi!
