### ISSUE TITLE
URL encoding/parsing breaks the component list

### ISSUE THREAD

**Issue by pokemane** [jgayfer/pydest#5]
Looks like the `encoded_url = urllib.parse.quote(url, safe=':/?&')` line in `_get_request()` needs a `=` and `,`.  Without them, the `?components=thing,thing` in the encoded URL gets the `=` and `,` replaced with their `%CODE` counterparts.  The API then returns Error Code 18, "The input parameters were invalid, please enter valid input, and try again."

**Comment by jgayfer** [comment]
Thank you for this. Try again with the latest build; I believe I have fixed the issue. Going to close this for now, but feel free to let me know if any problems persist!

**Comment by pokemane** [comment]
Yep, no problem.  Thanks!
