### ISSUE TITLE
Deploy to PyPi

### ISSUE THREAD

**Issue by russjr08** [jgayfer/pydest#8]
Hey there!

I'm looking to use pydest to create a [Home Assistant](https://www.home-assistant.io/) "sensor" which contains my game state. The build of Home Assistant that I'm using is called "HassIO", and for some reason, only allows custom sensors/components to use requirements that are found in PyPi. Would you be able to publish pydest up to PyPi? It would definitely help me, and I'm sure others, build with pydest! 

On a side note, I've found that while running pydest with the latest version of python, it seems to conflict with the current version of `aiohttp`. I was able to fix this by just forcing an update to 3.3.2 of aiohttp. The project may need to have the version bumped to the latest build.

If there's anything I can do to help, I'm all in! Python isn't my specialty, but I'm happy to lend a hand where I can.

**Comment by jgayfer** [comment]
Thanks for this! I will take a look at how things are running on the latest version of Python this week.

The only reason Pydest is not on PyPi is really just laziness on my part :) I should just go and do it. I didn't know there was interest!

**Comment by jgayfer** [comment]
Just pulled the project down and the integration tests are running fine with aiohttp 2.2.5 (the version specified in `requirements.txt`)

**Comment by russjr08** [comment]
Thanks! Yeah I’d definitely say go for it! Pydest is beautiful, I don’t think I’d have the ability to use the Destiny API alone without it. Also, I’ll take another look when I’m at home again, totally could just be me screwing up, but at the very least I can try to get a stacktrace if it’s still giving me some issues. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by russjr08** [comment]
Sorry it took me so long to get back to this, was actually in the hospital for a few days (yikes!). Here's the stack trace I'm getting.

```
Russells-MacBook-Pro:pydest russjr08$ python3
Python 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/russjr08/python_packages/pydest/pydest/__init__.py", line 4, in <module>
    from .api import API
  File "/Users/russjr08/python_packages/pydest/pydest/api.py", line 1, in <module>
    import aiohttp
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/connector.py", line 13, in <module>
    from . import hdrs, helpers
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/helpers.py", line 30
    ensure_future = asyncio.async
                                ^
SyntaxError: invalid syntax
```

However, updating aiohttp then returns no errors.

```
pydest 0.1.0 has requirement aiohttp==2.2.5, but you'll have aiohttp 3.3.2 which is incompatible.
Installing collected packages: attrs, aiohttp
  Found existing installation: aiohttp 2.2.5
    Uninstalling aiohttp-2.2.5:
      Successfully uninstalled aiohttp-2.2.5
Successfully installed aiohttp-3.3.2 attrs-18.1.0
Russells-MacBook-Pro:pydest russjr08$ python3
Python 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydest
>>>
```

**Comment by JAMeador13** [comment]
Hey, is this API wrapper complete and up to date? I was starting to make one myself, but then thought there might already be one. Also, I'm not familiar with asynchronous functionality; what is the benefit in this case?

**Comment by jgayfer** [comment]
It doesn't contain all of the endpoints, but it's still working and functional.

It's used as part of my Discord bot, which is all async, so it's somewhat tailored to my use case.

**Comment by russjr08** [comment]
Async is always handy to have anyways. You can easily turn async into sync if need be, but doing the reverse when it's not already built in can be difficult, so I'm glad that's implemented. 

Did anyone else ever run into the issue that I was having with needing to update libs? Also, @jgayfer any further thoughts on publishing out to PyPi? I'd still love to see it there!

**Comment by jgayfer** [comment]
I totally want it on PyPi, I just haven't been getting around to it! Admittedly I'd forgotten until just now.

**Comment by JAMeador13** [comment]
@russjr08 Good to know. I was making an API wrapper that would work for my discord bot, and the bot itself was asynchronous, but I had no idea if making the background stuff asynchronous would matter.

For the other endpoints, is anyone working on adding them in? I have some free time this week, and I can see if I can add a few of them in.

**Comment by jgayfer** [comment]
😂 

Yeah if your requests aren't async, it will brick your entire bot until the request completes, so it's important.

No one is currently working on adding additional endpoints as far as I know. Feel free to submit a PR adding any missing endpoints!

**Comment by JAMeador13** [comment]
Makes sense.

I'll look at it some over the next couple days and see if I can do a few of them. I did make a few changes in that script that might interest you though. They're very minor, but makes it cleaner.

**Comment by jgayfer** [comment]
Always looking for improvements!

**Comment by h3matite** [comment]
Hey James,

This seems absolutely fantastic, but I think I must be doing something wrong. I'm calling Search_Destiny_Player, and I'm getting information, but it's spewing warnings about not closing the client session, so I must be calling loop.close() incorrectly or something. Any thoughts?

Here's the basic code:
loop = asyncio.get_event_loop()
loop.run_until_complete(search_destiny_player(Name))
loop.close()

async def search_destiny_player(Name):
    destiny = pydest.Pydest("MyKey")
    res = await destiny.api.search_destiny_player("-1", Name)

    if res['ErrorCode'] == 1 and len(res['Response']) > 0:
        membershipID = format(res['Response'][0]['membershipId'])
        print("______ErrorStatus: "+ format(res['ErrorStatus']))
        print("Membership ID: " + membershipID)

This is the error I'm getting:
DEBUG:asyncio:Using selector: SelectSelector
WARNING:aiohttp.client:Can not load response cookies: Illegal key 'Q6dA7jjmn3WPG
kYAhga2oHvTT+8b849OPtfBrw@@'
______ErrorStatus: Success
Membership ID: 4611686018455038172
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000000004918128>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000000000B030
7C8>, 14275.245)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000000049182E8>

**Comment by jgayfer** [comment]
Alright, I'm committing to getting this project deployed to PyPl.

**Comment by jgayfer** [comment]
Done!
